# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
{{ if and .Values.externalSecretsOperator.enabled .Values.global.awsRegion }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalSecretsOperator.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ .Chart.Name }}
    kind: SecretStore
  target:
    name: {{ .Chart.Name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  {{- if .Values.externalSecretsOperator.externalSecret.data }}
  data:
    {{- range .Values.externalSecretsOperator.externalSecret.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{ if and .Values.externalSecretsOperator.enabled .Values.global.awsRegion .Values.app.ses.engagementSecretName }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.ses.engagementSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalSecretsOperator.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ .Chart.Name }}
    kind: SecretStore
  target:
    name: {{ .Values.app.ses.engagementSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: ses_configuration_set_name
      remoteRef:
        key: /cloudops/ses-managed/email-service-engagement
        property: ses_configuration_set_name
    - secretKey: sqs_queue_url
      remoteRef:
        key: /cloudops/ses-managed/email-service-engagement
        property: sqs_queue_url
{{- end }}
